services:
  - type: web
    name: lead-parser
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
