services:
  - type: web
    name: lead-parser
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
